### ISSUE TITLE
Use hlg-tools to go from HLG to PQ?

### ISSUE THREAD

**Issue by isaacolsen94** [wswartzendruber/hlg-tools#6]
Is it possible to use the hlg-tool to go from HLG to PQ hdr? I found this tool while trying to convert from HLG to PQ because the device I'm using doing support HLG, but I haven't been able to find anything that goes back to PQ since HLG is the better format. But since my device doesn't support it I need to go back.

**Comment by wswartzendruber** [comment]
The latest release has the `hlg2pq` utility that does what you're describing.

**Comment by isaacolsen94** [comment]
Oh awesome! Thanks! I'll give it a go today. Is there any documentation for that command?

**Comment by wswartzendruber** [comment]
`hlg2pq --help`

**Comment by wswartzendruber** [comment]
I'm closing this out for now.

**Comment by isaacolsen94** [comment]
Would it be possible to provide a step by step guide or video on doing the HLG to PQ run on Ubuntu or Windows? I've come back to this a few times and can't see to get it working
